const CURRENCY_CODE = 'USD';
const CURRENCY_SYMBOL = '$';
const CURRENCY_SYMBOL_LONG = 'US$';
const CURRENCY_SYMBOL_SHORT = 'U$';
const APP_URL = 'https://proton-s.net';
const APP_DOMAIN = 'proton-s.net';

export default {
  CURRENCY_CODE: CURRENCY_CODE,
  CURRENCY_SYMBOL: CURRENCY_SYMBOL,
  CURRENCY_SYMBOL_LONG: CURRENCY_SYMBOL_LONG,
  CURRENCY_SYMBOL_SHORT: CURRENCY_SYMBOL_SHORT,
  APP_URL: APP_URL,
  APP_DOMAIN: APP_DOMAIN
};
